import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="h-screen flex items-center justify-center">
				<p className="text-6xl text-center font-bold">Nastahran Rocks</p>
			</main>
		</div>
	);
};

export default Home;
